modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/MCCivilizations/Resources/issues"

[[mods]]
    modId="resources"
    version="${file.jarVersion}"
    displayName="McCivilizations: Resources"
    authors="DivineAspect, SkySom"
    description='''
        Adds the ability to tie abstract resources to a team.
    '''